user_present_list:     
    path: /users/present     
    defaults: { _controller: AppBundle:User:listPresent }

user_edit_person:
    path: /user/{id}/edit/person
    defaults: { _controller: AppBundle:User:editPerson }

user_upload:
    path: /user/{id}/image/{type}
    defaults: { _controller: AppBundle:User:uploadImages }

user_basic_show:
    path: /user/{id}/show/basic
    defaults: { _controller: AppBundle:User:showBasic }

file_download:
    path: /user/file/download/{fileName}
    defaults: { _controller: AppBundle:User:download }
